// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Cratis.VerticalSlices.CodeGeneration.Descriptors;

namespace Cratis.VerticalSlices.CodeGeneration.Renderers.Controller;

/// <summary>
/// Renders a command descriptor as a plain record plus an ASP.NET Core controller
/// with a POST endpoint that handles the command and appends events.
/// </summary>
public class ControllerCommandRenderer : IArtifactRenderer<CommandDescriptor>
{
    /// <inheritdoc/>
    public IEnumerable<RenderedArtifact> Render(CommandDescriptor descriptor, CodeGenerationContext context)
    {
        var producedEvents = descriptor.ProducedEvents.ToList();

        var isAutoGenerated = descriptor.EventSourceIdStrategy == EventSourceIdStrategy.AutoGenerated;

        var eventSourceIdType = context.Concepts.IsConcept(descriptor.EventSourceId)
            ? descriptor.EventSourceId
            : "EventSourceId";

        var allProperties = isAutoGenerated
            ? descriptor.Properties.Select(p => new Property(p.Name, p.Type))
            : new Property[] { new(descriptor.EventSourceId, eventSourceIdType) }
                .Concat(descriptor.Properties.Select(p => new Property(p.Name, p.Type)));

        var parameters = CodeWriter.FormatRecordParameters(allProperties);

        var propertyTypes = descriptor.Properties.Select(p => p.Type);
        if (!isAutoGenerated)
        {
            propertyTypes = propertyTypes.Append(eventSourceIdType);
        }

        var conceptUsings = context.Concepts.ResolveConceptUsings(
            propertyTypes,
            context.Namespace);

        // Render the command record (plain, no [Command] attribute)
        var commandBuilder = new CSharpCodeBuilder(context)
            .Using("Cratis.Chronicle.Events")
            .Using([.. conceptUsings])
            .Namespace(context.Namespace)
            .BlankLine();

        if (!string.IsNullOrWhiteSpace(descriptor.Description))
        {
            commandBuilder.Summary(descriptor.Description);
        }

        commandBuilder.Record(descriptor.Name, parameters);

        // Render the controller
        var controllerBuilder = new CSharpCodeBuilder(context)
            .Using("Cratis.Chronicle.Events", "Cratis.Chronicle.EventSequences", "Microsoft.AspNetCore.Mvc")
            .Using([.. conceptUsings])
            .Namespace(context.Namespace)
            .BlankLine()
            .Summary($"Handles the <see cref=\"{descriptor.Name}\"/> command.")
            .Attribute("ApiController")
            .Attribute("Route(\"api/[controller]\")");

        controllerBuilder.OpenClass($"{descriptor.Name}Controller", "ControllerBase");

        BuildHandleMethod(controllerBuilder, descriptor, producedEvents);

        controllerBuilder.EndBlock();

        var commandPath = Path.Combine(context.RelativePath, $"{descriptor.Name}.cs");
        var controllerPath = Path.Combine(context.RelativePath, $"{descriptor.Name}Controller.cs");

        return
        [
            new RenderedArtifact(commandPath, commandBuilder.ToString()),
            new RenderedArtifact(controllerPath, controllerBuilder.ToString())
        ];
    }

    static void BuildHandleMethod(
        CSharpCodeBuilder builder,
        CommandDescriptor descriptor,
        List<ProducedEventDescriptor> producedEvents)
    {
        builder
            .Summary($"Handles the {descriptor.Name} command.")
            .XmlParam("command", "The command to handle.")
            .XmlParam("eventLog", "The event log to append events to.")
            .Attribute("HttpPost")
            .OpenMethod("async Task<IActionResult>", "Handle", $"[FromBody] {descriptor.Name} command, [FromServices] IEventLog eventLog");

        if (descriptor.EventSourceIdStrategy == EventSourceIdStrategy.AutoGenerated)
        {
            builder.Statement("var eventSourceId = (EventSourceId)Guid.NewGuid().ToString();");
        }
        else
        {
            builder.Statement($"var eventSourceId = (EventSourceId)command.{descriptor.EventSourceId}.ToString();");
        }

        foreach (var produced in producedEvents)
        {
            var args = FormatEventArgs(produced);

            builder.Statement($"await eventLog.Append(eventSourceId, new {produced.EventType.Name}({args}));");
        }

        builder
            .Statement("return Ok();")
            .EndBlock();
    }

    static string FormatEventArgs(ProducedEventDescriptor produced) =>
        string.Join(", ", produced.PropertyMaps.Select(m => m.Source switch
        {
            ResolvedPropertyMapSource.FromCommand => $"command.{m.SourcePropertyName}",
            ResolvedPropertyMapSource.FromEventSourceId => "eventSourceId",
            _ => "default!"
        }));
}
