// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.VerticalSlices;

/// <summary>
/// Defines how the EventSourceId is obtained for a command.
/// </summary>
public enum EventSourceIdStrategy
{
    /// <summary>
    /// The caller must supply the event source id value when issuing the command.
    /// </summary>
    Supplied = 0,

    /// <summary>
    /// The event source id is auto-generated (e.g., <c>Guid.NewGuid()</c>) when the command is handled.
    /// </summary>
    AutoGenerated = 1
}
