// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.VerticalSlices.Integration.when_processing_a_state_view_module;

/// <summary>
/// End-to-end scenario: a bank-account style projection that uses Set, AddFrom, SubtractFrom
/// on the same Balance property — modelling deposits and withdrawals.
/// All three events are generated by a StateChange slice in the same module so that the event
/// types exist when the generated projection is compiled.
/// </summary>
public class with_arithmetic_balance_projection : given.a_real_engine
{
    IEnumerable<Module> _modules;

    void Establish()
    {
        // Three events used by the projection
        var accountOpened = new EventType(
            "AccountOpened",
            "A bank account was opened",
            [
                new Property("AccountId", "string"),
                new Property("InitialBalance", "decimal")
            ]);

        var depositMade = new EventType(
            "DepositMade",
            "A deposit was made",
            [
                new Property("AccountId", "string"),
                new Property("Amount", "decimal")
            ]);

        var withdrawalMade = new EventType(
            "WithdrawalMade",
            "A withdrawal was made",
            [
                new Property("AccountId", "string"),
                new Property("Amount", "decimal")
            ]);

        // StateChange slice so that the event type classes get generated
        var openAccountCommand = new Command(
            "OpenAccount",
            "Opens a new bank account",
            [
                new Property("InitialBalance", "decimal")
            ],
            "AccountId");

        var stateChangeSlice = new VerticalSlice(
            "AccountManagement",
            VerticalSliceType.StateChange,
            null,
            null,
            [openAccountCommand],
            [],
            [accountOpened, depositMade, withdrawalMade]);

        var accountFeature = new Feature("Accounts", [], [], [stateChangeSlice]);

        // Read model projecting the running balance
        var accountIdMapping = new[]
        {
            new EventPropertyMapping("AccountOpened", EventPropertyMappingKind.Set, "AccountId")
        };

        var balanceMappings = new[]
        {
            new EventPropertyMapping("AccountOpened", EventPropertyMappingKind.Set, "InitialBalance"),
            new EventPropertyMapping("DepositMade", EventPropertyMappingKind.Add, "Amount"),
            new EventPropertyMapping("WithdrawalMade", EventPropertyMappingKind.Subtract, "Amount")
        };

        var balanceReadModel = new ReadModel(
            "AccountBalance",
            "The running balance for an account",
            [
                new ReadModelProperty("AccountId", "string", accountIdMapping),
                new ReadModelProperty("Balance", "decimal", balanceMappings)
            ]);

        var stateViewSlice = new VerticalSlice(
            "BalanceView",
            VerticalSliceType.StateView,
            null,
            null,
            [],
            [balanceReadModel],
            [accountOpened, depositMade, withdrawalMade]);

        var balanceFeature = new Feature("BalanceView", [], [], [stateViewSlice]);

        _modules = [new Module("Banking", [], [accountFeature, balanceFeature])];
    }

    async Task Because()
    {
        await _engine.Process(_modules, _output);
        _generatedFiles = _engine.Preview(_modules);
        AddGlobalUsingsFromGeneratedFiles();
        _buildExitCode = await RunDotnet("build");
    }

    [Fact] void should_generate_projection_file() =>
        _generatedFiles.Any(f => f.RelativePath.EndsWith("AccountBalance.cs")).ShouldBeTrue();

    [Fact] void should_generate_observable_query_file() =>
        _generatedFiles.Any(f => f.RelativePath.EndsWith("AllAccountBalances.cs")).ShouldBeTrue();

    [Fact] void should_generate_all_three_event_type_files() =>
        new[] { "AccountOpened.cs", "DepositMade.cs", "WithdrawalMade.cs" }
            .All(name => _generatedFiles.Any(f => f.RelativePath.EndsWith(name)))
            .ShouldBeTrue();

    [Fact] void should_compile_successfully() => _buildExitCode.ShouldEqual(0);
}
