// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Cratis.VerticalSlices.CodeGeneration.Descriptors;

namespace Cratis.VerticalSlices.CodeGeneration.Renderers.ModelBound;

/// <summary>
/// Renders a command descriptor as an Arc model-bound [Command] record with a Handle method.
/// When the EventSourceId name matches a concept in scope, the property uses the concept type
/// (e.g., <c>PatientId PatientId</c>); otherwise it falls back to <c>EventSourceId</c>.
/// Handle() maps command properties to event constructor arguments by name.
/// </summary>
public class ModelBoundCommandRenderer : IArtifactRenderer<CommandDescriptor>
{
    /// <inheritdoc/>
    public IEnumerable<RenderedArtifact> Render(CommandDescriptor descriptor, CodeGenerationContext context)
    {
        var producedEvents = descriptor.ProducedEvents.ToList();
        var isAutoGenerated = descriptor.EventSourceIdStrategy == EventSourceIdStrategy.AutoGenerated;

        var eventSourceIdType = context.Concepts.IsConcept(descriptor.EventSourceId)
            ? descriptor.EventSourceId
            : "EventSourceId";

        var allProperties = isAutoGenerated
            ? descriptor.Properties.Select(p => new Property(p.Name, p.Type))
            : new Property[] { new(descriptor.EventSourceId, eventSourceIdType) }
                .Concat(descriptor.Properties.Select(p => new Property(p.Name, p.Type)));

        var parameters = CodeWriter.FormatRecordParameters(allProperties);

        var propertyTypes = descriptor.Properties.Select(p => p.Type);
        if (!isAutoGenerated)
        {
            propertyTypes = propertyTypes.Append(eventSourceIdType);
        }

        var conceptUsings = context.Concepts.ResolveConceptUsings(
            propertyTypes,
            context.Namespace);

        var builder = new CSharpCodeBuilder(context)
            .Using("Cratis.Arc.Commands.ModelBound")
            .Using("Cratis.Chronicle.Events")
            .Using([.. conceptUsings])
            .Namespace(context.Namespace)
            .BlankLine();

        if (!string.IsNullOrWhiteSpace(descriptor.Description))
        {
            builder.Summary(descriptor.Description);
        }

        builder.Attribute("Command");

        if (isAutoGenerated)
        {
            builder.Attribute("AutoGenerateEventSourceId");
        }

        builder.OpenRecord(descriptor.Name, parameters);

        if (producedEvents.Count == 1)
        {
            var produced = producedEvents[0];
            var args = FormatEventArgs(produced);

            builder
                .Summary($"Handles the {descriptor.Name} command.")
                .XmlReturns($"The <see cref=\"{produced.EventType.Name}\"/> event to append.")
                .ExpressionMember(produced.EventType.Name, "Handle", $"new({args});");
        }
        else if (producedEvents.Count > 1)
        {
            var eventInstances = string.Join(
                ", ",
                producedEvents.Select(produced =>
                {
                    var args = FormatEventArgs(produced);

                    return $"new {produced.EventType.Name}({args})";
                }));

            builder
                .Summary($"Handles the {descriptor.Name} command.")
                .XmlReturns("The events to append.")
                .ExpressionMember("IEnumerable<object>", "Handle", $"[{eventInstances}];");
        }
        else
        {
            builder
                .Summary($"Handles the {descriptor.Name} command.")
                .OpenMethod("void", "Handle")
                .EndBlock();
        }

        builder.EndBlock();

        var artifactPath = Path.Combine(context.RelativePath, $"{descriptor.Name}.cs");

        return [new RenderedArtifact(artifactPath, builder.ToString())];
    }

    static string FormatEventArgs(ProducedEventDescriptor produced) =>
        string.Join(", ", produced.PropertyMaps.Select(m => m.Source switch
        {
            ResolvedPropertyMapSource.FromCommand => m.SourcePropertyName!,
            _ => "default!"
        }));
}
