// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Cratis.VerticalSlices.CodeGeneration.Descriptors;

namespace Cratis.VerticalSlices.CodeGeneration.Renderers.Controller.for_ControllerCommandRenderer.when_rendering;

/// <summary>
/// Specs for rendering a controller command with auto-generated event source id.
/// </summary>
public class with_auto_generated_event_source_id : given.a_context
{
    ControllerCommandRenderer _renderer;
    CommandDescriptor _descriptor;
    string _controllerContent;

    void Establish()
    {
        _renderer = new ControllerCommandRenderer();
        _descriptor = new CommandDescriptor(
            "RegisterPatient",
            "Registers a patient",
            [new CommandPropertyDescriptor("Name", "string", null, null)],
            [new ProducedEventDescriptor(
                new EventTypeDescriptor("PatientRegistered", "A patient was registered", [new Property("PatientId", "string"), new Property("Name", "string")]),
                [
                    new ResolvedPropertyMap("PatientId", ResolvedPropertyMapSource.FromEventSourceId),
                    new ResolvedPropertyMap("Name", ResolvedPropertyMapSource.FromCommand, "Name")
                ])],
            "PatientId",
            EventSourceIdStrategy.AutoGenerated);
    }

    void Because() => _controllerContent = _renderer.Render(_descriptor, _context).Last().Content;

    [Fact] void should_auto_generate_event_source_id() => _controllerContent.ShouldContain("Guid.NewGuid()");
    [Fact] void should_not_read_event_source_id_from_command() => _controllerContent.ShouldNotContain("command.PatientId");

    [Fact]
    void should_not_include_event_source_id_in_command_record() =>
        _renderer.Render(_descriptor, _context).First().Content.ShouldNotContain("PatientId PatientId");
}
