// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.VerticalSlices.CodeGeneration.Descriptors;

/// <summary>
/// Describes the structure of a command, including the events it produces
/// with fully resolved property mappings, independent of how it will be rendered to code.
/// </summary>
/// <param name="Name">The command name.</param>
/// <param name="Description">A human-readable description of the command.</param>
/// <param name="Properties">The command's input properties with optional screen field metadata.</param>
/// <param name="ProducedEvents">The events this command produces with resolved property mappings.</param>
/// <param name="EventSourceId">The name of the property that acts as the event source id.</param>
/// <param name="EventSourceIdStrategy">How the event source id is obtained — supplied by the caller or auto-generated.</param>
public record CommandDescriptor(
    string Name,
    string Description,
    IEnumerable<CommandPropertyDescriptor> Properties,
    IEnumerable<ProducedEventDescriptor> ProducedEvents,
    string EventSourceId,
    EventSourceIdStrategy EventSourceIdStrategy = EventSourceIdStrategy.Supplied)
{
    /// <summary>
    /// Creates a <see cref="CommandDescriptor"/> from a <see cref="Command"/> and its produced events,
    /// matching screen fields to command properties by name and resolving all
    /// command-to-event property mappings.
    /// When <see cref="Command.ProducedEvents"/> is set, only those events are used;
    /// otherwise all <paramref name="producedEvents"/> are associated with the command.
    /// </summary>
    /// <param name="command">The command to describe.</param>
    /// <param name="producedEvents">The events available at the slice level.</param>
    /// <param name="screen">The optional screen whose fields map to command properties.</param>
    /// <param name="concepts">The concept scope used to filter event source id properties from produced events.</param>
    /// <returns>A new <see cref="CommandDescriptor"/>.</returns>
    public static CommandDescriptor FromCommand(Command command, IEnumerable<EventType> producedEvents, Screen? screen, ConceptScope concepts)
    {
        var screenFields = screen?.Fields.ToList() ?? [];

        var properties = command.Properties.Select(property =>
        {
            var matchingField = screenFields
                .FirstOrDefault(f => f.Name.Equals(property.Name, StringComparison.OrdinalIgnoreCase));

            return new CommandPropertyDescriptor(
                property.Name,
                property.Type,
                matchingField?.FieldType,
                matchingField?.Label);
        });

        var isAutoGenerated = command.EventSourceIdStrategy == EventSourceIdStrategy.AutoGenerated;

        var commandPropertyNames = new HashSet<string>(
            command.Properties.Select(p => p.Name), StringComparer.OrdinalIgnoreCase);

        if (!isAutoGenerated)
        {
            commandPropertyNames.Add(command.EventSourceId);
        }

        var effectiveEvents = ResolveProducedEvents(command, producedEvents);

        var resolvedEvents = effectiveEvents.Select(eventType =>
        {
            var eventDescriptor = EventTypeDescriptor.FromEventType(eventType, concepts);
            var mappings = ResolveMappings(eventDescriptor, commandPropertyNames, command.EventSourceId, isAutoGenerated);

            return new ProducedEventDescriptor(eventDescriptor, mappings);
        });

        return new CommandDescriptor(
            command.Name,
            command.Description,
            properties,
            resolvedEvents,
            command.EventSourceId,
            command.EventSourceIdStrategy);
    }

    /// <summary>
    /// Determines which events to associate with the command. When the command
    /// declares explicit <see cref="Command.ProducedEvents"/>, only matching events
    /// from the available set are used. Otherwise all available events are used.
    /// </summary>
    /// <param name="command">The command whose produced events to resolve.</param>
    /// <param name="availableEvents">The events available in the containing feature.</param>
    /// <returns>The resolved set of events the command produces.</returns>
    static IEnumerable<EventType> ResolveProducedEvents(Command command, IEnumerable<EventType> availableEvents)
    {
        if (command.ProducedEvents is null)
        {
            return availableEvents;
        }

        var declaredNames = new HashSet<string>(
            command.ProducedEvents.Select(p => p.EventTypeName), StringComparer.OrdinalIgnoreCase);

        return availableEvents.Where(e => declaredNames.Contains(e.Name));
    }

    /// <summary>
    /// Resolves how each event property gets its value from the command context.
    /// </summary>
    /// <param name="eventType">The event type descriptor whose properties are being mapped.</param>
    /// <param name="commandPropertyNames">The set of property names available on the command.</param>
    /// <param name="eventSourceIdName">The name of the event source identifier property.</param>
    /// <param name="isAutoGenerated">Whether the event source identifier is auto-generated.</param>
    /// <returns>The resolved property mappings for the event type.</returns>
    static IEnumerable<ResolvedPropertyMap> ResolveMappings(
        EventTypeDescriptor eventType,
        HashSet<string> commandPropertyNames,
        string eventSourceIdName,
        bool isAutoGenerated) =>
        eventType.Properties.Select(p =>
        {
            if (isAutoGenerated && p.Name.Equals(eventSourceIdName, StringComparison.OrdinalIgnoreCase))
            {
                return new ResolvedPropertyMap(p.Name, ResolvedPropertyMapSource.FromEventSourceId);
            }

            if (commandPropertyNames.Contains(p.Name))
            {
                return new ResolvedPropertyMap(p.Name, ResolvedPropertyMapSource.FromCommand, p.Name);
            }

            return new ResolvedPropertyMap(p.Name, ResolvedPropertyMapSource.ComputedDefault);
        });
}
