// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Cratis.DependencyInjection;

namespace Cratis.VerticalSlices.EventModelAdvisory.Rules;

/// <summary>
/// Detects commands that have no <see cref="Command.EventSourceId"/> value.
/// Every command must identify the aggregate or entity it targets so the generated
/// command handler can route the command to the correct event source.
/// </summary>
[Singleton]
public class MissingEventSourceIdRule : IEventModelRule
{
    /// <inheritdoc/>
    public IEnumerable<EventModelRecommendation> Evaluate(IEnumerable<Module> modules)
    {
        foreach (var (moduleName, path, slice) in modules.FlattenSlices()
            .Where(item => item.Slice.SliceType != VerticalSliceType.Translator))
        {
            foreach (var command in slice.Commands.Where(c => string.IsNullOrWhiteSpace(c.EventSourceId)))
            {
                yield return new EventModelRecommendation(
                    EventModelRecommendationSeverity.Error,
                    EventModelRecommendationCategory.Structure,
                    moduleName,
                    path,
                    slice.Name,
                    command.Name,
                    $"Command '{command.Name}' must have an EventSourceId. The event source id must either be supplied as a command property or use the AutoGenerated strategy.",
                    "Set EventSourceId to a property name and use EventSourceIdStrategy.Supplied, or set the strategy to EventSourceIdStrategy.AutoGenerated.");
            }
        }
    }
}
