// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.VerticalSlices.EventModelAdvisory.Rules;

/// <summary>
/// Detects commands that have no <see cref="Command.EventSourceId"/> value.
/// Every command must identify the aggregate or entity it targets so the generated
/// command handler can route the command to the correct event source. A missing
/// event source id means the generated code cannot bind the command to any event
/// stream and will fail at runtime or compile time.
/// </summary>
public class MissingEventSourceIdRule : IEventModelRule
{
    /// <inheritdoc/>
    public IEnumerable<EventModelRecommendation> Evaluate(IEnumerable<Module> modules)
    {
        foreach (var module in modules)
        {
            foreach (var recommendation in EvaluateFeatures(module.Features, module.Name, FeaturePath.Empty))
            {
                yield return recommendation;
            }
        }
    }

    static IEnumerable<EventModelRecommendation> EvaluateFeatures(IEnumerable<Feature> features, string moduleName, FeaturePath path)
    {
        foreach (var feature in features)
        {
            var featurePath = path.Append(feature.Name);
            foreach (var slice in feature.VerticalSlices.Where(s => s.SliceType != VerticalSliceType.Translator))
            {
                foreach (var command in slice.Commands.Where(c => string.IsNullOrWhiteSpace(c.EventSourceId)))
                {
                    yield return new EventModelRecommendation(
                        EventModelRecommendationSeverity.Error,
                        EventModelRecommendationCategory.Structure,
                        moduleName,
                        featurePath,
                        slice.Name,
                        command.Name,
                        $"Command '{command.Name}' must have an EventSourceId. The event source id must either be supplied as a command property or use the AutoGenerated strategy.",
                        "Set EventSourceId to a property name and use EventSourceIdStrategy.Supplied, or set the strategy to EventSourceIdStrategy.AutoGenerated.");
                }
            }

            foreach (var recommendation in EvaluateFeatures(feature.Features, moduleName, featurePath))
            {
                yield return recommendation;
            }
        }
    }
}
