// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Cratis.VerticalSlices.CodeGeneration.Descriptors;

namespace Cratis.VerticalSlices.CodeGeneration.Renderers.ModelBound.for_ModelBoundCommandRenderer.when_rendering;

/// <summary>
/// Specs for rendering a command with auto-generated event source id.
/// </summary>
public class with_auto_generated_event_source_id : given.a_context
{
    ModelBoundCommandRenderer _renderer;
    CommandDescriptor _descriptor;
    string _content;

    void Establish()
    {
        _renderer = new ModelBoundCommandRenderer();
        _descriptor = new CommandDescriptor(
            "RegisterPatient",
            "Registers a new patient",
            [new CommandPropertyDescriptor("Name", "string", null, null)],
            [new ProducedEventDescriptor(
                new EventTypeDescriptor("PatientRegistered", "A patient was registered", [new Property("PatientId", "string"), new Property("Name", "string")]),
                [
                    new ResolvedPropertyMap("PatientId", ResolvedPropertyMapSource.FromEventSourceId),
                    new ResolvedPropertyMap("Name", ResolvedPropertyMapSource.FromCommand, "Name")
                ])],
            "PatientId",
            EventSourceIdStrategy.AutoGenerated);
    }

    void Because() => _content = _renderer.Render(_descriptor, _context).Single().Content;

    [Fact] void should_emit_auto_generate_attribute() => _content.ShouldContain("[AutoGenerateEventSourceId]");
    [Fact] void should_not_include_event_source_id_as_property() => _content.ShouldNotContain("EventSourceId PatientId");
    [Fact] void should_include_name_property() => _content.ShouldContain("string Name");
    [Fact] void should_emit_command_attribute() => _content.ShouldContain("[Command]");
    [Fact] void should_map_name_arg() => _content.ShouldContain("Name");
    [Fact] void should_use_default_for_unmapped_patient_id() => _content.ShouldContain("default!");
}
