// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.VerticalSlices.Integration.when_processing;

/// <summary>
/// Fixture that builds the full multi-module scenario and runs code generation + compilation once.
/// Uses short, context-relative names throughout (e.g. "Create" instead of "CreateInvoice")
/// because the feature path already provides the domain context.
/// </summary>
public class MultiModuleFixture : given.EngineFixture
{
    /// <inheritdoc/>
    public override async Task InitializeAsync()
    {
        await base.InitializeAsync();
        await ProcessAndBuild(BuildModules());
    }

    static IEnumerable<Module> BuildModules()
    {
        // ═══════════════════════════════════════════════════════════════════════
        //  Module 1: Healthcare
        //    Concepts: PatientId (EventSourceId), Email
        //    Features: Registration (FullName), Appointments (AppointmentId)
        // ═══════════════════════════════════════════════════════════════════════

        var patientId = new Concept("PatientId", "Guid", "Uniquely identifies a patient", [], IsEventSourceId: true);
        var email = new Concept(
            "Email",
            "string",
            "An email address",
            [
                new ConceptValidationRule(ConceptValidationRuleType.NotEmpty),
                new ConceptValidationRule(ConceptValidationRuleType.EmailAddress)
            ]);

        // Feature: Registration — concept: FullName
        var fullName = new Concept(
            "FullName",
            "string",
            "A person's full name",
            [
                new ConceptValidationRule(ConceptValidationRuleType.NotEmpty),
                new ConceptValidationRule(ConceptValidationRuleType.MaximumLength, "200")
            ]);

        var registered = new EventType(
            "Registered",
            "A patient was registered in the system",
            [
                new Property("PatientId", "PatientId"),
                new Property("Name", "FullName"),
                new Property("ContactEmail", "Email"),
                new Property("DateOfBirth", "DateTimeOffset")
            ]);

        var registerScreen = new Screen(
            "RegisterForm",
            "Captures new patient details",
            [
                new ScreenField("Name", "FullName", ScreenFieldType.TextInput, "Full name"),
                new ScreenField("ContactEmail", "Email", ScreenFieldType.TextInput, "Email address"),
                new ScreenField("DateOfBirth", "DateTimeOffset", ScreenFieldType.Date, "Date of birth")
            ]);

        var registerCommand = new Command(
            "Register",
            "Registers a new patient",
            [
                new Property("Name", "FullName"),
                new Property("ContactEmail", "Email"),
                new Property("DateOfBirth", "DateTimeOffset")
            ],
            "PatientId",
            EventSourceIdStrategy.AutoGenerated);

        var registerSlice = new VerticalSlice(
            "Register",
            VerticalSliceType.StateChange,
            "Captures a new patient registration and emits the Registered event.",
            registerScreen,
            [registerCommand],
            [],
            [registered]);

        var summaryIdMappings = new[] { new EventPropertyMapping("Registered", EventPropertyMappingKind.FromEventSourceId) };
        var summaryNameMappings = new[] { new EventPropertyMapping("Registered", EventPropertyMappingKind.Set, "Name") };
        var summaryEmailMappings = new[] { new EventPropertyMapping("Registered", EventPropertyMappingKind.Set, "ContactEmail") };
        var summaryRegisteredAtMappings = new[] { new EventPropertyMapping("Registered", EventPropertyMappingKind.SetFromContext, "Occurred") };

        var summary = new ReadModel(
            "Summary",
            "A summary of a registered patient",
            [
                new ReadModelProperty("PatientId", "PatientId", summaryIdMappings),
                new ReadModelProperty("Name", "FullName", summaryNameMappings),
                new ReadModelProperty("ContactEmail", "Email", summaryEmailMappings),
                new ReadModelProperty("RegisteredAt", "DateTimeOffset", summaryRegisteredAtMappings)
            ]);

        var viewSlice = new VerticalSlice(
            "View",
            VerticalSliceType.StateView,
            null,
            null,
            [],
            [summary],
            [registered]);

        var registrationFeature = new Feature(
            "Registration",
            [fullName],
            [],
            [registerSlice, viewSlice]);

        // Feature: Appointments — concept: AppointmentId
        var appointmentId = new Concept("AppointmentId", "Guid", "Uniquely identifies an appointment", [], IsEventSourceId: true);

        var scheduled = new EventType(
            "Scheduled",
            "An appointment was scheduled",
            [
                new Property("AppointmentId", "AppointmentId"),
                new Property("DoctorName", "string"),
                new Property("ScheduledAt", "DateTimeOffset")
            ]);

        var scheduleCommand = new Command(
            "Schedule",
            "Schedules a new appointment",
            [
                new Property("DoctorName", "string"),
                new Property("ScheduledAt", "DateTimeOffset")
            ],
            "AppointmentId",
            EventSourceIdStrategy.AutoGenerated);

        var scheduleSlice = new VerticalSlice(
            "Schedule",
            VerticalSliceType.StateChange,
            null,
            null,
            [scheduleCommand],
            [],
            [scheduled]);

        var cancelled = new EventType(
            "Cancelled",
            "An appointment was cancelled",
            [
                new Property("AppointmentId", "AppointmentId"),
                new Property("Reason", "string")
            ]);

        var cancelCommand = new Command(
            "Cancel",
            "Cancels an appointment",
            [new Property("Reason", "string")],
            "AppointmentId");

        var cancelSlice = new VerticalSlice(
            "Cancel",
            VerticalSliceType.StateChange,
            null,
            null,
            [cancelCommand],
            [],
            [cancelled]);

        var schedulingSubFeature = new Feature("Scheduling", [], [], [scheduleSlice, cancelSlice]);

        // Sub-feature: Calendar — Translator
        var externalEvent = new EventType(
            "External",
            "An event from the external calendar system",
            [new Property("ExternalRef", "string")],
            EventKind.External);

        var synced = new EventType(
            "Synced",
            "An external calendar event was synced",
            [
                new Property("AppointmentId", "AppointmentId"),
                new Property("ExternalRef", "string")
            ]);

        var syncSlice = new VerticalSlice(
            "Sync",
            VerticalSliceType.Translator,
            null,
            null,
            [],
            [],
            [externalEvent, synced]);

        var calendarSubFeature = new Feature("Calendar", [], [], [syncSlice]);

        var appointmentsFeature = new Feature(
            "Appointments",
            [appointmentId],
            [schedulingSubFeature, calendarSubFeature],
            []);

        var healthcareModule = new Module("Healthcare", [patientId, email], [registrationFeature, appointmentsFeature]);

        // ═══════════════════════════════════════════════════════════════════════
        //  Module 2: Billing
        //    Concepts: InvoiceId (EventSourceId), Amount (GreaterThan 0)
        //    Features: Invoicing (InvoiceNumber), Payments
        // ═══════════════════════════════════════════════════════════════════════

        var invoiceId = new Concept("InvoiceId", "Guid", "Uniquely identifies an invoice", [], IsEventSourceId: true);
        var amount = new Concept(
            "Amount",
            "decimal",
            "A monetary amount",
            [new ConceptValidationRule(ConceptValidationRuleType.GreaterThan, "0")]);

        // Feature: Invoicing — concept: InvoiceNumber
        var invoiceNumber = new Concept(
            "InvoiceNumber",
            "string",
            "A human-readable invoice number",
            [
                new ConceptValidationRule(ConceptValidationRuleType.NotEmpty),
                new ConceptValidationRule(ConceptValidationRuleType.Pattern, @"^INV-\d+$")
            ]);

        var created = new EventType(
            "Created",
            "An invoice was created",
            [
                new Property("InvoiceId", "InvoiceId"),
                new Property("InvoiceNumber", "InvoiceNumber"),
                new Property("TotalAmount", "Amount"),
                new Property("CustomerId", "string")
            ]);

        var createCommand = new Command(
            "Create",
            "Creates a new invoice",
            [
                new Property("InvoiceNumber", "InvoiceNumber"),
                new Property("TotalAmount", "Amount"),
                new Property("CustomerId", "string")
            ],
            "InvoiceId",
            EventSourceIdStrategy.AutoGenerated);

        var createSlice = new VerticalSlice(
            "Create",
            VerticalSliceType.StateChange,
            null,
            null,
            [createCommand],
            [],
            [created]);

        var overviewIdMappings = new[] { new EventPropertyMapping("Created", EventPropertyMappingKind.FromEventSourceId) };
        var overviewNumberMappings = new[] { new EventPropertyMapping("Created", EventPropertyMappingKind.Set, "InvoiceNumber") };
        var overviewAmountMappings = new[] { new EventPropertyMapping("Created", EventPropertyMappingKind.Set, "TotalAmount") };
        var overviewCustomerMappings = new[] { new EventPropertyMapping("Created", EventPropertyMappingKind.Set, "CustomerId") };

        var overview = new ReadModel(
            "Overview",
            "Overview of a created invoice",
            [
                new ReadModelProperty("InvoiceId", "InvoiceId", overviewIdMappings),
                new ReadModelProperty("InvoiceNumber", "InvoiceNumber", overviewNumberMappings),
                new ReadModelProperty("TotalAmount", "Amount", overviewAmountMappings),
                new ReadModelProperty("CustomerId", "string", overviewCustomerMappings)
            ]);

        var overviewSlice = new VerticalSlice(
            "Overview",
            VerticalSliceType.StateView,
            null,
            null,
            [],
            [overview],
            [created]);

        // Automation: Remind
        var reminded = new EventType(
            "Reminded",
            "A payment reminder was sent for an invoice",
            [
                new Property("InvoiceId", "InvoiceId"),
                new Property("ReminderCount", "int"),
                new Property("Message", "string")
            ]);

        var unpaidIdMappings = new[] { new EventPropertyMapping("Created", EventPropertyMappingKind.FromEventSourceId) };
        var unpaidAmountMappings = new[] { new EventPropertyMapping("Created", EventPropertyMappingKind.Set, "TotalAmount") };

        var unpaid = new ReadModel(
            "Unpaid",
            "An invoice that has not been paid yet",
            [
                new ReadModelProperty("InvoiceId", "InvoiceId", unpaidIdMappings),
                new ReadModelProperty("TotalAmount", "Amount", unpaidAmountMappings)
            ]);

        var remindCommand = new Command(
            "Remind",
            "Sends a payment reminder",
            [
                new Property("ReminderCount", "int"),
                new Property("Message", "string")
            ],
            "InvoiceId");

        var remindSlice = new VerticalSlice(
            "Remind",
            VerticalSliceType.Automation,
            null,
            null,
            [remindCommand],
            [unpaid],
            [reminded]);

        var invoicingFeature = new Feature(
            "Invoicing",
            [invoiceNumber],
            [],
            [createSlice, overviewSlice, remindSlice]);

        // Feature: Payments — no feature-level concepts
        var recorded = new EventType(
            "Recorded",
            "A payment was recorded against an invoice",
            [
                new Property("InvoiceId", "InvoiceId"),
                new Property("PaidAmount", "Amount"),
                new Property("PaidAt", "DateTimeOffset")
            ]);

        var recordCommand = new Command(
            "Record",
            "Records a payment against an invoice",
            [
                new Property("PaidAmount", "Amount"),
                new Property("PaidAt", "DateTimeOffset")
            ],
            "InvoiceId");

        var recordSlice = new VerticalSlice(
            "Record",
            VerticalSliceType.StateChange,
            null,
            null,
            [recordCommand],
            [],
            [recorded]);

        var paymentsFeature = new Feature("Payments", [], [], [recordSlice]);

        var billingModule = new Module("Billing", [invoiceId, amount], [invoicingFeature, paymentsFeature]);

        // ═══════════════════════════════════════════════════════════════════════
        //  Module 3: Notifications
        //    Concepts: NotificationId (EventSourceId)
        //    Features: Email, Push (DeviceToken)
        // ═══════════════════════════════════════════════════════════════════════

        var notificationId = new Concept("NotificationId", "Guid", "Uniquely identifies a notification", [], IsEventSourceId: true);

        // Feature: Email — Translator + StateView
        var externalDelivered = new EventType(
            "ExternalDelivered",
            "Email delivery confirmation from external provider",
            [
                new Property("MessageId", "string"),
                new Property("Recipient", "string")
            ],
            EventKind.External);

        var delivered = new EventType(
            "Delivered",
            "An email was confirmed as delivered internally",
            [
                new Property("NotificationId", "NotificationId"),
                new Property("Recipient", "string")
            ]);

        var ingestSlice = new VerticalSlice(
            "Ingest",
            VerticalSliceType.Translator,
            null,
            null,
            [],
            [],
            [externalDelivered, delivered]);

        var deliveryIdMappings = new[] { new EventPropertyMapping("Delivered", EventPropertyMappingKind.FromEventSourceId) };
        var deliveryRecipientMappings = new[] { new EventPropertyMapping("Delivered", EventPropertyMappingKind.Set, "Recipient") };
        var deliveryAtMappings = new[] { new EventPropertyMapping("Delivered", EventPropertyMappingKind.SetFromContext, "Occurred") };

        var delivery = new ReadModel(
            "Delivery",
            "A record of a delivered email notification",
            [
                new ReadModelProperty("NotificationId", "NotificationId", deliveryIdMappings),
                new ReadModelProperty("Recipient", "string", deliveryRecipientMappings),
                new ReadModelProperty("DeliveredAt", "DateTimeOffset", deliveryAtMappings)
            ]);

        var logSlice = new VerticalSlice(
            "Log",
            VerticalSliceType.StateView,
            null,
            null,
            [],
            [delivery],
            [delivered]);

        var emailFeature = new Feature("Email", [], [], [ingestSlice, logSlice]);

        // Feature: Push — concept: DeviceToken
        var deviceToken = new Concept(
            "DeviceToken",
            "string",
            "A push notification device token",
            [
                new ConceptValidationRule(ConceptValidationRuleType.NotEmpty),
                new ConceptValidationRule(ConceptValidationRuleType.MinimumLength, "10")
            ]);

        var sent = new EventType(
            "Sent",
            "A push notification was sent to a device",
            [
                new Property("NotificationId", "NotificationId"),
                new Property("DeviceToken", "DeviceToken"),
                new Property("Title", "string"),
                new Property("Body", "string")
            ]);

        var sendCommand = new Command(
            "Send",
            "Sends a push notification",
            [
                new Property("DeviceToken", "DeviceToken"),
                new Property("Title", "string"),
                new Property("Body", "string")
            ],
            "NotificationId");

        var sendSlice = new VerticalSlice(
            "Send",
            VerticalSliceType.StateChange,
            null,
            null,
            [sendCommand],
            [],
            [sent]);

        var pushFeature = new Feature("Push", [deviceToken], [], [sendSlice]);

        var notificationsModule = new Module("Notifications", [notificationId], [emailFeature, pushFeature]);

        return [healthcareModule, billingModule, notificationsModule];
    }
}
