// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Cratis.VerticalSlices.CodeGeneration;

namespace Cratis.VerticalSlices.Integration.when_processing;

/// <summary>
/// <para>
/// Comprehensive end-to-end scenario exercising the full engine pipeline across four
/// independent modules, each with a varying number of features containing different
/// slice types and domain concepts declared at every scope level. Uses short,
/// context-relative names throughout (e.g. "Create" instead of "CreateInvoice").
/// </para>
/// <para>Module layout:</para>
/// <para>
/// <b>Healthcare</b> (concepts: PatientId, Email)
///   - Registration (concept: FullName)
///       - Register (StateChange, AutoGenerated, Screen with TextArea) — FullName, Email concepts.
///       - View (StateView) — read model with FromEventSourceId mapping.
///   - Appointments (concept: AppointmentId)
///       - Scheduling
///           - Schedule (StateChange, AutoGenerated).
///           - Cancel (StateChange, Supplied).
///           - Rescheduling (3rd level nesting)
///               - Reschedule (StateChange, multi-event Handle producing 2 events).
///       - Calendar
///           - Sync (Translator + Command + ReadModel).
/// </para>
/// <para>
/// <b>Billing</b> (concepts: InvoiceId, Amount with GreaterThan)
///   - Invoicing (concept: InvoiceNumber with Pattern)
///       - Create (StateChange, AutoGenerated, explicit ProducedEvents, Screen with Number + Dropdown).
///       - Overview (StateView) — different-name Set, Add, Count, Increment, FromEvery mappings.
///       - Remind (Automation) — command has properties mapped to produced event.
///   - Payments
///       - Record (StateChange, Supplied).
///       - Refund (StateChange, Supplied).
///       - Balance (StateView) — Add, Subtract, Count, Decrement mappings.
/// </para>
/// <para>
/// <b>Notifications</b> (concept: NotificationId)
///   - Email
///       - Ingest (Translator + Command).
///       - Log (StateView) — FromEventSourceId + SetFromContext mappings.
///   - Push (concept: DeviceToken with MinimumLength)
///       - Send (StateChange, Supplied) — cross-namespace concept reference.
/// </para>
/// <para>
/// <b>Inventory</b> (concepts: ProductId, Quantity=int, Rating=double, IsDiscontinued=bool)
///   - Catalog (concepts: Sku, Discount with LessThan + Message)
///       - Add (StateChange, AutoGenerated, explicit ProducedEvents, Screen with Number + Checkbox + Dropdown).
///       - Restock (StateChange, multi-event Handle).
///       - Categories > Subcategories (3 level nesting)
///           - Categorize (StateChange).
///   - Tracking (concepts: ManufacturedOn=DateOnly, ShiftStart=TimeOnly)
///       - Ship (StateChange) — exercises date/time concept types.
/// </para>
/// <para>
/// The test writes all generated files to disk and compiles them with <c>dotnet build</c>,
/// verifying concept-type resolution, event source id filtering, cross-namespace
/// <see langword="using"/> directives, translator commands, explicit ProducedEvents,
/// multi-event Handle, all mapping kinds, deep nesting, and compilable output.
/// The fixture runs setup once for all facts.
/// </para>
/// </summary>
/// <param name="fixture">The shared fixture that runs engine setup once for all facts.</param>
public class with_multiple_modules_features_and_concepts(MultiModuleFixture fixture) : IClassFixture<MultiModuleFixture>
{
    readonly IEnumerable<RenderedArtifact> _generatedFiles = fixture.GeneratedFiles;
    readonly int _buildExitCode = fixture.BuildExitCode;

    // ── Healthcare module ──────────────────────────────────────────────────────
    [Fact] void should_generate_healthcare_module_concept_files() =>
        new[] { "PatientId.cs", "Email.cs" }
            .All(name => _generatedFiles.Any(f => f.ArtifactPath.Contains("Healthcare") && f.ArtifactPath.EndsWith(name)))
            .ShouldBeTrue();

    [Fact] void should_generate_registration_feature_concept() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Registration") && f.ArtifactPath.EndsWith("FullName.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_appointments_feature_concept() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Appointments") && f.ArtifactPath.EndsWith("AppointmentId.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_register_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Registration") && f.ArtifactPath.EndsWith("Register.cs"))
            .ShouldBeTrue();

    [Fact] void should_include_registered_event_in_register_slice() =>
        SliceContent("Registration", "Register.cs").ShouldContain("record Registered");

    [Fact] void should_include_summary_read_model_in_view_slice() =>
        SliceContent("Registration", "View.cs").ShouldContain("record Summary");

    [Fact] void should_generate_scheduling_command_files() =>
        new[] { "Schedule.cs", "Cancel.cs" }
            .All(name => _generatedFiles.Any(f => f.ArtifactPath.Contains("Scheduling") && f.ArtifactPath.EndsWith(name)))
            .ShouldBeTrue();

    [Fact] void should_include_synced_event_in_sync_slice() =>
        SliceContent("Calendar", "Sync.cs").ShouldContain("record Synced");

    [Fact] void should_not_generate_translator_external_event() =>
        _generatedFiles.Any(f => f.ArtifactPath.EndsWith("External.cs"))
            .ShouldBeFalse();

    // ── Healthcare: 3rd-level nesting (Rescheduling) ───────────────────────────
    [Fact] void should_generate_reschedule_slice_at_third_level() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Rescheduling") && f.ArtifactPath.EndsWith("Reschedule.cs"))
            .ShouldBeTrue();

    [Fact] void should_use_multi_event_handle_for_reschedule() =>
        SliceContent("Rescheduling", "Reschedule.cs").ShouldContain("IEnumerable<object>");

    [Fact] void should_include_rescheduled_event_in_reschedule_slice() =>
        SliceContent("Rescheduling", "Reschedule.cs").ShouldContain("record Rescheduled");

    [Fact] void should_include_rescheduling_notified_event_in_reschedule_slice() =>
        SliceContent("Rescheduling", "Reschedule.cs").ShouldContain("record ReschedulingNotified");

    // ── Healthcare: Translator with ReadModel + Command ────────────────────────
    [Fact] void should_include_sync_log_read_model_in_translator() =>
        SliceContent("Calendar", "Sync.cs").ShouldContain("record SyncLog");

    [Fact] void should_include_translator_command_in_sync_slice() =>
        SliceContent("Calendar", "Sync.cs").ShouldContain("record Sync(");

    // ── Billing module ─────────────────────────────────────────────────────────
    [Fact] void should_generate_billing_module_concept_files() =>
        new[] { "InvoiceId.cs", "Amount.cs" }
            .All(name => _generatedFiles.Any(f => f.ArtifactPath.Contains("Billing") && f.ArtifactPath.EndsWith(name)))
            .ShouldBeTrue();

    [Fact] void should_generate_invoicing_feature_concept() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Invoicing") && f.ArtifactPath.EndsWith("InvoiceNumber.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_create_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Invoicing") && f.ArtifactPath.EndsWith("Create.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_overview_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Invoicing") && f.ArtifactPath.EndsWith("Overview.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_remind_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Invoicing") && f.ArtifactPath.EndsWith("Remind.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_record_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Payments") && f.ArtifactPath.EndsWith("Record.cs"))
            .ShouldBeTrue();

    // ── Billing: LineAdded event ────────────────────────────────────────────────
    [Fact] void should_include_line_added_event_in_create_slice() =>
        SliceContent("Invoicing", "Create.cs").ShouldContain("record LineAdded");

    // ── Billing: Explicit ProducedEvents on Create command ─────────────────────
    [Fact] void should_produce_only_created_event_from_create_command() =>
        SliceContent("Invoicing", "Create.cs").ShouldContain("Created Handle");

    [Fact] void should_not_produce_line_added_from_create_handle() =>
        RegexMatch(SliceContent("Invoicing", "Create.cs"), @"Handle\(\)[^;]*;")
            .ShouldNotContain("LineAdded");

    // ── Billing: Overview read model mapping attributes ────────────────────────
    [Fact] void should_use_from_event_attribute_for_same_name_set_on_overview() =>
        SliceContent("Invoicing", "Overview.cs").ShouldContain("FromEvent<Created>");

    [Fact] void should_use_set_from_for_different_name_on_overview() =>
        SliceContent("Invoicing", "Overview.cs").ShouldContain("SetFrom<Created>(nameof(Created.CustomerId))");

    [Fact] void should_use_add_from_attribute_on_overview() =>
        SliceContent("Invoicing", "Overview.cs").ShouldContain("AddFrom<LineAdded>(nameof(LineAdded.LineAmount))");

    [Fact] void should_use_count_attribute_on_overview() =>
        SliceContent("Invoicing", "Overview.cs").ShouldContain("Count<LineAdded>");

    [Fact] void should_use_increment_attribute_on_overview() =>
        SliceContent("Invoicing", "Overview.cs").ShouldContain("Increment<LineAdded>");

    [Fact] void should_use_from_every_attribute_on_overview() =>
        SliceContent("Invoicing", "Overview.cs").ShouldContain("FromEvery(contextProperty: nameof(EventContext.Occurred))");

    // ── Billing: Refund slice ──────────────────────────────────────────────────
    [Fact] void should_generate_refund_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Payments") && f.ArtifactPath.EndsWith("Refund.cs"))
            .ShouldBeTrue();

    [Fact] void should_include_refunded_event_in_refund_slice() =>
        SliceContent("Payments", "Refund.cs").ShouldContain("record Refunded");

    // ── Billing: Balance read model mapping attributes ─────────────────────────
    [Fact] void should_generate_balance_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Payments") && f.ArtifactPath.EndsWith("Balance.cs"))
            .ShouldBeTrue();

    [Fact] void should_use_add_from_attribute_on_balance() =>
        SliceContent("Payments", "Balance.cs").ShouldContain("AddFrom<Recorded>(nameof(Recorded.PaidAmount))");

    [Fact] void should_use_subtract_from_attribute_on_balance() =>
        SliceContent("Payments", "Balance.cs").ShouldContain("SubtractFrom<Refunded>(nameof(Refunded.RefundedAmount))");

    [Fact] void should_use_count_attribute_on_balance() =>
        SliceContent("Payments", "Balance.cs").ShouldContain("Count<Recorded>");

    [Fact] void should_use_decrement_attribute_on_balance() =>
        SliceContent("Payments", "Balance.cs").ShouldContain("Decrement<Refunded>");

    // ── Notifications module ───────────────────────────────────────────────────
    [Fact] void should_generate_notification_module_concept() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Notifications") && f.ArtifactPath.EndsWith("NotificationId.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_push_feature_concept() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Push") && f.ArtifactPath.EndsWith("DeviceToken.cs"))
            .ShouldBeTrue();

    [Fact] void should_include_delivered_event_in_ingest_slice() =>
        SliceContent("Email", "Ingest.cs").ShouldContain("record Delivered");

    [Fact] void should_not_generate_email_translator_external_event() =>
        _generatedFiles.Any(f => f.ArtifactPath.EndsWith("ExternalDelivered.cs"))
            .ShouldBeFalse();

    [Fact] void should_include_delivery_read_model_in_log_slice() =>
        SliceContent("Email", "Log.cs").ShouldContain("record Delivery");

    [Fact] void should_generate_send_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Push") && f.ArtifactPath.EndsWith("Send.cs"))
            .ShouldBeTrue();

    // ── Concept types in generated code ────────────────────────────────────────
    [Fact] void should_use_concept_types_in_event_properties() =>
        SliceContent("Registration", "Register.cs").ShouldContain("FullName Name");

    [Fact] void should_use_concept_types_in_command_properties() =>
        SliceContent("Registration", "Register.cs").ShouldContain("FullName Name");

    [Fact] void should_use_concept_types_in_read_model_properties() =>
        SliceContent("Registration", "View.cs").ShouldContain("FullName Name");

    [Fact] void should_use_billing_concept_in_payment_event() =>
        SliceContent("Payments", "Record.cs").ShouldContain("Amount PaidAmount");

    // ── Event source id filtering ──────────────────────────────────────────────
    [Fact] void should_filter_event_source_id_from_registered_event() =>
        RegexMatch(SliceContent("Registration", "Register.cs"), @"record Registered\([^)]*\)")
            .ShouldNotContain("PatientId");

    // ── AutoGenerated strategy ─────────────────────────────────────────────────
    [Fact] void should_use_auto_generated_attribute_on_register_command() =>
        SliceContent("Registration", "Register.cs").ShouldContain("AutoGenerateEventSourceId");

    [Fact] void should_use_auto_generated_attribute_on_create_command() =>
        SliceContent("Invoicing", "Create.cs").ShouldContain("AutoGenerateEventSourceId");

    // ── Supplied strategy (no AutoGenerate attribute) ──────────────────────────
    [Fact] void should_not_use_auto_generated_attribute_on_cancel_command() =>
        SliceContent("Scheduling", "Cancel.cs").ShouldNotContain("AutoGenerateEventSourceId");

    // ── Automation command produces event ───────────────────────────────────────
    [Fact] void should_include_reminded_event_in_remind_slice() =>
        SliceContent("Invoicing", "Remind.cs").ShouldContain("record Reminded");

    [Fact] void should_map_remind_command_properties_to_event() =>
        SliceContent("Invoicing", "Remind.cs").ShouldContain("ReminderCount");

    // ── Cross-namespace concept using ──────────────────────────────────────────
    [Fact] void should_add_concept_using_for_cross_namespace_reference() =>
        SliceContent("Push", "Send.cs").ShouldContain("using Notifications;");

    // ── Inventory module: concept files ────────────────────────────────────────
    [Fact] void should_generate_inventory_module_concept_files() =>
        new[] { "ProductId.cs", "Quantity.cs", "Rating.cs", "IsDiscontinued.cs" }
            .All(name => _generatedFiles.Any(f => f.ArtifactPath.Contains("Inventory") && f.ArtifactPath.EndsWith(name)))
            .ShouldBeTrue();

    [Fact] void should_generate_catalog_feature_concept_files() =>
        new[] { "Sku.cs", "Discount.cs" }
            .All(name => _generatedFiles.Any(f => f.ArtifactPath.Contains("Catalog") && f.ArtifactPath.EndsWith(name)))
            .ShouldBeTrue();

    [Fact] void should_generate_tracking_feature_concept_files() =>
        new[] { "ManufacturedOn.cs", "ShiftStart.cs" }
            .All(name => _generatedFiles.Any(f => f.ArtifactPath.Contains("Tracking") && f.ArtifactPath.EndsWith(name)))
            .ShouldBeTrue();

    // ── Inventory: int concept (Quantity) ──────────────────────────────────────
    [Fact] void should_use_int_underlying_type_for_quantity_concept() =>
        ConceptContent("Inventory", "Quantity.cs").ShouldContain("ConceptAs<int>");

    [Fact] void should_include_not_set_default_for_int_concept() =>
        ConceptContent("Inventory", "Quantity.cs").ShouldContain("new(Value: 0)");

    [Fact] void should_include_greater_than_or_equal_to_with_message_on_quantity() =>
        ConceptContent("Inventory", "Quantity.cs").ShouldContain(".GreaterThanOrEqualTo(0).WithMessage(\"Quantity must be non-negative\")");

    // ── Inventory: double concept (Rating) ─────────────────────────────────────
    [Fact] void should_use_double_underlying_type_for_rating_concept() =>
        ConceptContent("Inventory", "Rating.cs").ShouldContain("ConceptAs<double>");

    [Fact] void should_include_less_than_or_equal_to_with_message_on_rating() =>
        ConceptContent("Inventory", "Rating.cs").ShouldContain(".LessThanOrEqualTo(5).WithMessage(\"Rating must not exceed 5\")");

    // ── Inventory: bool concept (IsDiscontinued) ───────────────────────────────
    [Fact] void should_use_bool_underlying_type_for_is_discontinued_concept() =>
        ConceptContent("Inventory", "IsDiscontinued.cs").ShouldContain("ConceptAs<bool>");

    [Fact] void should_not_include_not_set_default_for_bool_concept() =>
        ConceptContent("Inventory", "IsDiscontinued.cs").ShouldNotContain("NotSet");

    // ── Inventory: DateOnly concept (ManufacturedOn) ───────────────────────────
    [Fact] void should_use_date_only_underlying_type_for_manufactured_on_concept() =>
        ConceptContent("Tracking", "ManufacturedOn.cs").ShouldContain("ConceptAs<DateOnly>");

    [Fact] void should_include_date_only_min_value_default() =>
        ConceptContent("Tracking", "ManufacturedOn.cs").ShouldContain("DateOnly.MinValue");

    // ── Inventory: TimeOnly concept (ShiftStart) ───────────────────────────────
    [Fact] void should_use_time_only_underlying_type_for_shift_start_concept() =>
        ConceptContent("Tracking", "ShiftStart.cs").ShouldContain("ConceptAs<TimeOnly>");

    [Fact] void should_include_time_only_min_value_default() =>
        ConceptContent("Tracking", "ShiftStart.cs").ShouldContain("TimeOnly.MinValue");

    // ── Inventory: LessThan validation with message (Discount) ─────────────────
    [Fact] void should_include_less_than_with_message_on_discount() =>
        ConceptContent("Catalog", "Discount.cs").ShouldContain(".LessThan(100).WithMessage(\"Discount must be less than 100%\")");

    // ── Inventory: Add slice with explicit ProducedEvents + ComputedDefault ────
    [Fact] void should_generate_add_slice_in_catalog() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Catalog") && f.ArtifactPath.EndsWith("Add.cs"))
            .ShouldBeTrue();

    [Fact] void should_include_product_added_event_in_add_slice() =>
        SliceContent("Catalog", "Add.cs").ShouldContain("record ProductAdded");

    [Fact] void should_include_price_set_event_in_add_slice() =>
        SliceContent("Catalog", "Add.cs").ShouldContain("record PriceSet");

    [Fact] void should_use_auto_generated_on_add_product_command() =>
        SliceContent("Catalog", "Add.cs").ShouldContain("AutoGenerateEventSourceId");

    [Fact] void should_produce_only_product_added_from_add_handle() =>
        SliceContent("Catalog", "Add.cs").ShouldContain("ProductAdded Handle");

    [Fact] void should_use_computed_default_for_unmapped_event_property() =>
        SliceContent("Catalog", "Add.cs").ShouldContain("default!");

    // ── Inventory: Restock multi-event command ─────────────────────────────────
    [Fact] void should_generate_restock_slice_in_catalog() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Catalog") && f.ArtifactPath.EndsWith("Restock.cs"))
            .ShouldBeTrue();

    [Fact] void should_use_multi_event_handle_for_restock() =>
        SliceContent("Catalog", "Restock.cs").ShouldContain("IEnumerable<object>");

    [Fact] void should_include_restocked_event_in_restock_slice() =>
        SliceContent("Catalog", "Restock.cs").ShouldContain("record Restocked");

    [Fact] void should_include_inventory_adjusted_event_in_restock_slice() =>
        SliceContent("Catalog", "Restock.cs").ShouldContain("record InventoryAdjusted");

    // ── Inventory: 3-level nesting (Categories > Subcategories) ────────────────
    [Fact] void should_generate_categorize_slice_at_third_level() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Subcategories") && f.ArtifactPath.EndsWith("Categorize.cs"))
            .ShouldBeTrue();

    [Fact] void should_include_categorized_event_in_categorize_slice() =>
        SliceContent("Subcategories", "Categorize.cs").ShouldContain("record Categorized");

    // ── Inventory: Tracking with date/time concepts ────────────────────────────
    [Fact] void should_generate_ship_slice_in_tracking() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Tracking") && f.ArtifactPath.EndsWith("Ship.cs"))
            .ShouldBeTrue();

    [Fact] void should_use_manufactured_on_concept_in_shipped_event() =>
        SliceContent("Tracking", "Ship.cs").ShouldContain("ManufacturedOn ManufacturedOn");

    [Fact] void should_use_shift_start_concept_in_shipped_event() =>
        SliceContent("Tracking", "Ship.cs").ShouldContain("ShiftStart ShiftStart");

    // ── Inventory: Quantity concept used in event properties ───────────────────
    [Fact] void should_use_quantity_concept_in_add_product_event() =>
        SliceContent("Catalog", "Add.cs").ShouldContain("Quantity InitialQuantity");

    [Fact] void should_use_quantity_concept_in_restock_event() =>
        SliceContent("Catalog", "Restock.cs").ShouldContain("Quantity AddedQuantity");

    // ── Compilation ────────────────────────────────────────────────────────────
    [Fact] void should_compile_successfully() => _buildExitCode.ShouldEqual(0);

    string SliceContent(string pathSegment, string fileName) =>
        _generatedFiles
            .First(f => f.ArtifactPath.Contains(pathSegment) && f.ArtifactPath.EndsWith(fileName))
            .Content;

    string ConceptContent(string pathSegment, string fileName) =>
        _generatedFiles
            .First(f => f.ArtifactPath.Contains(pathSegment) && f.ArtifactPath.EndsWith(fileName))
            .Content;

    static string RegexMatch(string input, string pattern) =>
        System.Text.RegularExpressions.Regex.Match(input, pattern).Value;
}
