// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Cratis.VerticalSlices.CodeGeneration;

namespace Cratis.VerticalSlices.Integration.when_processing;

/// <summary>
/// <para>
/// Comprehensive end-to-end scenario exercising the full engine pipeline across three
/// independent modules, each with a varying number of features containing different
/// slice types and domain concepts declared at every scope level. Uses short,
/// context-relative names throughout (e.g. "Create" instead of "CreateInvoice").
/// </para>
/// <para>Module layout:</para>
/// <para>
/// <b>Healthcare</b> (concepts: PatientId, Email)
///   - Registration (concept: FullName)
///       - Register (StateChange, AutoGenerated, Screen) — FullName, Email concepts.
///       - View (StateView) — read model with FromEventSourceId mapping.
///   - Appointments (concept: AppointmentId)
///       - Scheduling
///           - Schedule (StateChange, AutoGenerated).
///           - Cancel (StateChange, Supplied).
///       - Calendar
///           - Sync (Translator).
/// </para>
/// <para>
/// <b>Billing</b> (concepts: InvoiceId, Amount with GreaterThan)
///   - Invoicing (concept: InvoiceNumber with Pattern)
///       - Create (StateChange, AutoGenerated).
///       - Overview (StateView) — FromEventSourceId mapping.
///       - Remind (Automation) — command has properties mapped to produced event.
///   - Payments
///       - Record (StateChange, Supplied).
/// </para>
/// <para>
/// <b>Notifications</b> (concept: NotificationId)
///   - Email
///       - Ingest (Translator).
///       - Log (StateView) — FromEventSourceId + SetFromContext mappings.
///   - Push (concept: DeviceToken with MinimumLength)
///       - Send (StateChange, Supplied) — cross-namespace concept reference.
/// </para>
/// <para>
/// The test writes all generated files to disk and compiles them with <c>dotnet build</c>,
/// verifying concept-type resolution, event source id filtering, cross-namespace
/// <see langword="using"/> directives, and compilable output.
/// The fixture runs setup once for all facts.
/// </para>
/// </summary>
/// <param name="fixture">The shared fixture that runs engine setup once for all facts.</param>
public class with_multiple_modules_features_and_concepts(MultiModuleFixture fixture) : IClassFixture<MultiModuleFixture>
{
    readonly IEnumerable<RenderedArtifact> _generatedFiles = fixture.GeneratedFiles;
    readonly int _buildExitCode = fixture.BuildExitCode;

    // ── Healthcare module ──────────────────────────────────────────────────────
    [Fact] void should_generate_healthcare_module_concept_files() =>
        new[] { "PatientId.cs", "Email.cs" }
            .All(name => _generatedFiles.Any(f => f.ArtifactPath.Contains("Healthcare") && f.ArtifactPath.EndsWith(name)))
            .ShouldBeTrue();

    [Fact] void should_generate_registration_feature_concept() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Registration") && f.ArtifactPath.EndsWith("FullName.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_appointments_feature_concept() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Appointments") && f.ArtifactPath.EndsWith("AppointmentId.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_register_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Registration") && f.ArtifactPath.EndsWith("Register.cs"))
            .ShouldBeTrue();

    [Fact] void should_include_registered_event_in_register_slice() =>
        SliceContent("Registration", "Register.cs").ShouldContain("record Registered");

    [Fact] void should_include_summary_read_model_in_view_slice() =>
        SliceContent("Registration", "View.cs").ShouldContain("record Summary");

    [Fact] void should_generate_scheduling_command_files() =>
        new[] { "Schedule.cs", "Cancel.cs" }
            .All(name => _generatedFiles.Any(f => f.ArtifactPath.Contains("Scheduling") && f.ArtifactPath.EndsWith(name)))
            .ShouldBeTrue();

    [Fact] void should_include_synced_event_in_sync_slice() =>
        SliceContent("Calendar", "Sync.cs").ShouldContain("record Synced");

    [Fact] void should_not_generate_translator_external_event() =>
        _generatedFiles.Any(f => f.ArtifactPath.EndsWith("External.cs"))
            .ShouldBeFalse();

    // ── Billing module ─────────────────────────────────────────────────────────
    [Fact] void should_generate_billing_module_concept_files() =>
        new[] { "InvoiceId.cs", "Amount.cs" }
            .All(name => _generatedFiles.Any(f => f.ArtifactPath.Contains("Billing") && f.ArtifactPath.EndsWith(name)))
            .ShouldBeTrue();

    [Fact] void should_generate_invoicing_feature_concept() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Invoicing") && f.ArtifactPath.EndsWith("InvoiceNumber.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_create_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Invoicing") && f.ArtifactPath.EndsWith("Create.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_overview_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Invoicing") && f.ArtifactPath.EndsWith("Overview.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_remind_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Invoicing") && f.ArtifactPath.EndsWith("Remind.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_record_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Payments") && f.ArtifactPath.EndsWith("Record.cs"))
            .ShouldBeTrue();

    // ── Notifications module ───────────────────────────────────────────────────
    [Fact] void should_generate_notification_module_concept() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Notifications") && f.ArtifactPath.EndsWith("NotificationId.cs"))
            .ShouldBeTrue();

    [Fact] void should_generate_push_feature_concept() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Push") && f.ArtifactPath.EndsWith("DeviceToken.cs"))
            .ShouldBeTrue();

    [Fact] void should_include_delivered_event_in_ingest_slice() =>
        SliceContent("Email", "Ingest.cs").ShouldContain("record Delivered");

    [Fact] void should_not_generate_email_translator_external_event() =>
        _generatedFiles.Any(f => f.ArtifactPath.EndsWith("ExternalDelivered.cs"))
            .ShouldBeFalse();

    [Fact] void should_include_delivery_read_model_in_log_slice() =>
        SliceContent("Email", "Log.cs").ShouldContain("record Delivery");

    [Fact] void should_generate_send_slice_file() =>
        _generatedFiles.Any(f => f.ArtifactPath.Contains("Push") && f.ArtifactPath.EndsWith("Send.cs"))
            .ShouldBeTrue();

    // ── Concept types in generated code ────────────────────────────────────────
    [Fact] void should_use_concept_types_in_event_properties() =>
        SliceContent("Registration", "Register.cs").ShouldContain("FullName Name");

    [Fact] void should_use_concept_types_in_command_properties() =>
        SliceContent("Registration", "Register.cs").ShouldContain("FullName Name");

    [Fact] void should_use_concept_types_in_read_model_properties() =>
        SliceContent("Registration", "View.cs").ShouldContain("FullName Name");

    [Fact] void should_use_billing_concept_in_payment_event() =>
        SliceContent("Payments", "Record.cs").ShouldContain("Amount PaidAmount");

    // ── Event source id filtering ──────────────────────────────────────────────
    [Fact] void should_filter_event_source_id_from_registered_event() =>
        RegexMatch(SliceContent("Registration", "Register.cs"), @"record Registered\([^)]*\)")
            .ShouldNotContain("PatientId");

    // ── AutoGenerated strategy ─────────────────────────────────────────────────
    [Fact] void should_use_auto_generated_attribute_on_register_command() =>
        SliceContent("Registration", "Register.cs").ShouldContain("AutoGenerateEventSourceId");

    [Fact] void should_use_auto_generated_attribute_on_create_command() =>
        SliceContent("Invoicing", "Create.cs").ShouldContain("AutoGenerateEventSourceId");

    // ── Supplied strategy (no AutoGenerate attribute) ──────────────────────────
    [Fact] void should_not_use_auto_generated_attribute_on_cancel_command() =>
        SliceContent("Scheduling", "Cancel.cs").ShouldNotContain("AutoGenerateEventSourceId");

    // ── Automation command produces event ───────────────────────────────────────
    [Fact] void should_include_reminded_event_in_remind_slice() =>
        SliceContent("Invoicing", "Remind.cs").ShouldContain("record Reminded");

    [Fact] void should_map_remind_command_properties_to_event() =>
        SliceContent("Invoicing", "Remind.cs").ShouldContain("ReminderCount");

    // ── Cross-namespace concept using ──────────────────────────────────────────
    [Fact] void should_add_concept_using_for_cross_namespace_reference() =>
        SliceContent("Push", "Send.cs").ShouldContain("using Notifications;");

    // ── Compilation ────────────────────────────────────────────────────────────
    [Fact] void should_compile_successfully() => _buildExitCode.ShouldEqual(0);

    string SliceContent(string pathSegment, string fileName) =>
        _generatedFiles
            .First(f => f.ArtifactPath.Contains(pathSegment) && f.ArtifactPath.EndsWith(fileName))
            .Content;

    static string RegexMatch(string input, string pattern) =>
        System.Text.RegularExpressions.Regex.Match(input, pattern).Value;
}
