// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Cratis.VerticalSlices.EventModelAdvisory;
using Cratis.VerticalSlices.EventModelAdvisory.Rules;

namespace Cratis.VerticalSlices.for_EventSourceIdPropertyNotFoundRule.when_evaluating;

public class with_auto_generated_strategy_and_no_matching_property : Specification
{
    static Module[] _modules;
    IEnumerable<EventModelRecommendation> _result;

    void Establish()
    {
        // AutoGenerated strategy — the EventSourceId property need not exist in Properties
        var command = new Command(
            "PlaceOrder",
            "Places an order",
            [
                new Property("Amount", "decimal")
            ],
            "OrderId",
            EventSourceIdStrategy.AutoGenerated);
        var slice = new VerticalSlice("PlaceOrder", VerticalSliceType.StateChange, null, null, [command], [], []);
        _modules = [new Module("Orders", [], [new Feature("Ordering", [], [], [slice])])];
    }

    void Because() => _result = new EventSourceIdPropertyNotFoundRule().Evaluate(_modules);

    [Fact] void should_return_no_recommendations() => _result.ShouldBeEmpty();
}
